INSERT INTO countries (code, name_en, name_ar, ear_group, is_embargoed, diversion_risk) VALUES
  ('AD', 'Andorra', NULL, NULL, FALSE, 0),
  ('AE', 'United Arab Emirates', 'الإمارات العربية المتحدة', 'B', FALSE, 2),
  ('AF', 'Afghanistan', NULL, NULL, FALSE, 0),
  ('AG', 'Antigua & Barbuda', NULL, NULL, FALSE, 0),
  ('AI', 'Anguilla', NULL, NULL, FALSE, 0),
  ('AL', 'Albania', NULL, NULL, FALSE, 0),
  ('AM', 'Armenia', NULL, NULL, FALSE, 0),
  ('AO', 'Angola', NULL, NULL, FALSE, 0),
  ('AQ', 'Antarctica', NULL, NULL, FALSE, 0),
  ('AR', 'Argentina', NULL, NULL, FALSE, 0),
  ('AS', 'American Samoa', NULL, NULL, FALSE, 0),
  ('AT', 'Austria', NULL, NULL, FALSE, 0),
  ('AU', 'Australia', NULL, NULL, FALSE, 0),
  ('AW', 'Aruba', NULL, NULL, FALSE, 0),
  ('AX', 'Åland Islands', NULL, NULL, FALSE, 0),
  ('AZ', 'Azerbaijan', NULL, NULL, FALSE, 0),
  ('BA', 'Bosnia & Herzegovina', NULL, NULL, FALSE, 0),
  ('BB', 'Barbados', NULL, NULL, FALSE, 0),
  ('BD', 'Bangladesh', NULL, NULL, FALSE, 0),
  ('BE', 'Belgium', NULL, NULL, FALSE, 0),
  ('BF', 'Burkina Faso', NULL, NULL, FALSE, 0),
  ('BG', 'Bulgaria', NULL, NULL, FALSE, 0),
  ('BH', 'Bahrain', 'البحرين', 'B', FALSE, 1),
  ('BI', 'Burundi', NULL, NULL, FALSE, 0),
  ('BJ', 'Benin', NULL, NULL, FALSE, 0),
  ('BL', 'St. Barthélemy', NULL, NULL, FALSE, 0),
  ('BM', 'Bermuda', NULL, NULL, FALSE, 0),
  ('BN', 'Brunei', NULL, NULL, FALSE, 0),
  ('BO', 'Bolivia', NULL, NULL, FALSE, 0),
  ('BQ', 'Caribbean Netherlands', NULL, NULL, FALSE, 0),
  ('BR', 'Brazil', NULL, NULL, FALSE, 0),
  ('BS', 'Bahamas', NULL, NULL, FALSE, 0),
  ('BT', 'Bhutan', NULL, NULL, FALSE, 0),
  ('BV', 'Bouvet Island', NULL, NULL, FALSE, 0),
  ('BW', 'Botswana', NULL, NULL, FALSE, 0),
  ('BY', 'Belarus', NULL, NULL, FALSE, 0),
  ('BZ', 'Belize', NULL, NULL, FALSE, 0),
  ('CA', 'Canada', NULL, NULL, FALSE, 0),
  ('CC', 'Cocos (Keeling) Islands', NULL, NULL, FALSE, 0),
  ('CD', 'Congo - Kinshasa', NULL, NULL, FALSE, 0),
  ('CF', 'Central African Republic', NULL, NULL, FALSE, 0),
  ('CG', 'Congo - Brazzaville', NULL, NULL, FALSE, 0),
  ('CH', 'Switzerland', NULL, NULL, FALSE, 0),
  ('CI', 'Côte d’Ivoire', NULL, NULL, FALSE, 0),
  ('CK', 'Cook Islands', NULL, NULL, FALSE, 0),
  ('CL', 'Chile', NULL, NULL, FALSE, 0),
  ('CM', 'Cameroon', NULL, NULL, FALSE, 0),
  ('CN', 'China', 'الصين', 'D:1', FALSE, 4),
  ('CO', 'Colombia', NULL, NULL, FALSE, 0),
  ('CR', 'Costa Rica', NULL, NULL, FALSE, 0),
  ('CU', 'Cuba', 'كوبا', 'E:1', TRUE, 5),
  ('CV', 'Cape Verde', NULL, NULL, FALSE, 0),
  ('CW', 'Curaçao', NULL, NULL, FALSE, 0),
  ('CX', 'Christmas Island', NULL, NULL, FALSE, 0),
  ('CY', 'Cyprus', NULL, NULL, FALSE, 0),
  ('CZ', 'Czechia', NULL, NULL, FALSE, 0),
  ('DE', 'Germany', 'ألمانيا', 'A:1', FALSE, 0),
  ('DJ', 'Djibouti', NULL, NULL, FALSE, 0),
  ('DK', 'Denmark', NULL, NULL, FALSE, 0),
  ('DM', 'Dominica', NULL, NULL, FALSE, 0),
  ('DO', 'Dominican Republic', NULL, NULL, FALSE, 0),
  ('DZ', 'Algeria', NULL, NULL, FALSE, 0),
  ('EC', 'Ecuador', NULL, NULL, FALSE, 0),
  ('EE', 'Estonia', NULL, NULL, FALSE, 0),
  ('EG', 'Egypt', NULL, NULL, FALSE, 0),
  ('EH', 'Western Sahara', NULL, NULL, FALSE, 0),
  ('ER', 'Eritrea', NULL, NULL, FALSE, 0),
  ('ES', 'Spain', NULL, NULL, FALSE, 0),
  ('ET', 'Ethiopia', NULL, NULL, FALSE, 0),
  ('FI', 'Finland', NULL, NULL, FALSE, 0),
  ('FJ', 'Fiji', NULL, NULL, FALSE, 0),
  ('FK', 'Falkland Islands', NULL, NULL, FALSE, 0),
  ('FM', 'Micronesia', NULL, NULL, FALSE, 0),
  ('FO', 'Faroe Islands', NULL, NULL, FALSE, 0),
  ('FR', 'France', NULL, NULL, FALSE, 0),
  ('GA', 'Gabon', NULL, NULL, FALSE, 0),
  ('GB', 'United Kingdom', 'المملكة المتحدة', 'A:1', FALSE, 0),
  ('GD', 'Grenada', NULL, NULL, FALSE, 0),
  ('GE', 'Georgia', NULL, NULL, FALSE, 0),
  ('GF', 'French Guiana', NULL, NULL, FALSE, 0),
  ('GG', 'Guernsey', NULL, NULL, FALSE, 0),
  ('GH', 'Ghana', NULL, NULL, FALSE, 0),
  ('GI', 'Gibraltar', NULL, NULL, FALSE, 0),
  ('GL', 'Greenland', NULL, NULL, FALSE, 0),
  ('GM', 'Gambia', NULL, NULL, FALSE, 0),
  ('GN', 'Guinea', NULL, NULL, FALSE, 0),
  ('GP', 'Guadeloupe', NULL, NULL, FALSE, 0),
  ('GQ', 'Equatorial Guinea', NULL, NULL, FALSE, 0),
  ('GR', 'Greece', NULL, NULL, FALSE, 0),
  ('GS', 'South Georgia & South Sandwich Islands', NULL, NULL, FALSE, 0),
  ('GT', 'Guatemala', NULL, NULL, FALSE, 0),
  ('GU', 'Guam', NULL, NULL, FALSE, 0),
  ('GW', 'Guinea-Bissau', NULL, NULL, FALSE, 0),
  ('GY', 'Guyana', NULL, NULL, FALSE, 0),
  ('HK', 'Hong Kong SAR China', NULL, NULL, FALSE, 0),
  ('HM', 'Heard & McDonald Islands', NULL, NULL, FALSE, 0),
  ('HN', 'Honduras', NULL, NULL, FALSE, 0),
  ('HR', 'Croatia', NULL, NULL, FALSE, 0),
  ('HT', 'Haiti', NULL, NULL, FALSE, 0),
  ('HU', 'Hungary', NULL, NULL, FALSE, 0),
  ('ID', 'Indonesia', NULL, NULL, FALSE, 0),
  ('IE', 'Ireland', NULL, NULL, FALSE, 0),
  ('IL', 'Israel', NULL, NULL, FALSE, 0),
  ('IM', 'Isle of Man', NULL, NULL, FALSE, 0),
  ('IN', 'India', NULL, NULL, FALSE, 0),
  ('IO', 'British Indian Ocean Territory', NULL, NULL, FALSE, 0),
  ('IQ', 'Iraq', NULL, NULL, FALSE, 0),
  ('IR', 'Iran', 'إيران', 'E:1', TRUE, 5),
  ('IS', 'Iceland', NULL, NULL, FALSE, 0),
  ('IT', 'Italy', NULL, NULL, FALSE, 0),
  ('JE', 'Jersey', NULL, NULL, FALSE, 0),
  ('JM', 'Jamaica', NULL, NULL, FALSE, 0),
  ('JO', 'Jordan', NULL, NULL, FALSE, 0),
  ('JP', 'Japan', NULL, NULL, FALSE, 0),
  ('KE', 'Kenya', NULL, NULL, FALSE, 0),
  ('KG', 'Kyrgyzstan', NULL, NULL, FALSE, 0),
  ('KH', 'Cambodia', NULL, NULL, FALSE, 0),
  ('KI', 'Kiribati', NULL, NULL, FALSE, 0),
  ('KM', 'Comoros', NULL, NULL, FALSE, 0),
  ('KN', 'St. Kitts & Nevis', NULL, NULL, FALSE, 0),
  ('KP', 'North Korea', 'كوريا الشمالية', 'E:1', TRUE, 5),
  ('KR', 'South Korea', NULL, NULL, FALSE, 0),
  ('KW', 'Kuwait', 'الكويت', 'B', FALSE, 1),
  ('KY', 'Cayman Islands', NULL, NULL, FALSE, 0),
  ('KZ', 'Kazakhstan', NULL, NULL, FALSE, 0),
  ('LA', 'Laos', NULL, NULL, FALSE, 0),
  ('LB', 'Lebanon', NULL, NULL, FALSE, 0),
  ('LC', 'St. Lucia', NULL, NULL, FALSE, 0),
  ('LI', 'Liechtenstein', NULL, NULL, FALSE, 0),
  ('LK', 'Sri Lanka', NULL, NULL, FALSE, 0),
  ('LR', 'Liberia', NULL, NULL, FALSE, 0),
  ('LS', 'Lesotho', NULL, NULL, FALSE, 0),
  ('LT', 'Lithuania', NULL, NULL, FALSE, 0),
  ('LU', 'Luxembourg', NULL, NULL, FALSE, 0),
  ('LV', 'Latvia', NULL, NULL, FALSE, 0),
  ('LY', 'Libya', NULL, NULL, FALSE, 0),
  ('MA', 'Morocco', NULL, NULL, FALSE, 0),
  ('MC', 'Monaco', NULL, NULL, FALSE, 0),
  ('MD', 'Moldova', NULL, NULL, FALSE, 0),
  ('ME', 'Montenegro', NULL, NULL, FALSE, 0),
  ('MF', 'St. Martin', NULL, NULL, FALSE, 0),
  ('MG', 'Madagascar', NULL, NULL, FALSE, 0),
  ('MH', 'Marshall Islands', NULL, NULL, FALSE, 0),
  ('MK', 'North Macedonia', NULL, NULL, FALSE, 0),
  ('ML', 'Mali', NULL, NULL, FALSE, 0),
  ('MM', 'Myanmar (Burma)', NULL, NULL, FALSE, 0),
  ('MN', 'Mongolia', NULL, NULL, FALSE, 0),
  ('MO', 'Macao SAR China', NULL, NULL, FALSE, 0),
  ('MP', 'Northern Mariana Islands', NULL, NULL, FALSE, 0),
  ('MQ', 'Martinique', NULL, NULL, FALSE, 0),
  ('MR', 'Mauritania', NULL, NULL, FALSE, 0),
  ('MS', 'Montserrat', NULL, NULL, FALSE, 0),
  ('MT', 'Malta', NULL, NULL, FALSE, 0),
  ('MU', 'Mauritius', NULL, NULL, FALSE, 0),
  ('MV', 'Maldives', NULL, NULL, FALSE, 0),
  ('MW', 'Malawi', NULL, NULL, FALSE, 0),
  ('MX', 'Mexico', NULL, NULL, FALSE, 0),
  ('MY', 'Malaysia', NULL, NULL, FALSE, 0),
  ('MZ', 'Mozambique', NULL, NULL, FALSE, 0),
  ('NA', 'Namibia', NULL, NULL, FALSE, 0),
  ('NC', 'New Caledonia', NULL, NULL, FALSE, 0),
  ('NE', 'Niger', NULL, NULL, FALSE, 0),
  ('NF', 'Norfolk Island', NULL, NULL, FALSE, 0),
  ('NG', 'Nigeria', NULL, NULL, FALSE, 0),
  ('NI', 'Nicaragua', NULL, NULL, FALSE, 0),
  ('NL', 'Netherlands', NULL, NULL, FALSE, 0),
  ('NO', 'Norway', NULL, NULL, FALSE, 0),
  ('NP', 'Nepal', NULL, NULL, FALSE, 0),
  ('NR', 'Nauru', NULL, NULL, FALSE, 0),
  ('NU', 'Niue', NULL, NULL, FALSE, 0),
  ('NZ', 'New Zealand', NULL, NULL, FALSE, 0),
  ('OM', 'Oman', 'عُمان', 'B', FALSE, 2),
  ('PA', 'Panama', NULL, NULL, FALSE, 0),
  ('PE', 'Peru', NULL, NULL, FALSE, 0),
  ('PF', 'French Polynesia', NULL, NULL, FALSE, 0),
  ('PG', 'Papua New Guinea', NULL, NULL, FALSE, 0),
  ('PH', 'Philippines', NULL, NULL, FALSE, 0),
  ('PK', 'Pakistan', NULL, NULL, FALSE, 0),
  ('PL', 'Poland', NULL, NULL, FALSE, 0),
  ('PM', 'St. Pierre & Miquelon', NULL, NULL, FALSE, 0),
  ('PN', 'Pitcairn Islands', NULL, NULL, FALSE, 0),
  ('PR', 'Puerto Rico', NULL, NULL, FALSE, 0),
  ('PS', 'Palestinian Territories', NULL, NULL, FALSE, 0),
  ('PT', 'Portugal', NULL, NULL, FALSE, 0),
  ('PW', 'Palau', NULL, NULL, FALSE, 0),
  ('PY', 'Paraguay', NULL, NULL, FALSE, 0),
  ('QA', 'Qatar', 'قطر', 'B', FALSE, 1),
  ('RE', 'Réunion', NULL, NULL, FALSE, 0),
  ('RO', 'Romania', NULL, NULL, FALSE, 0),
  ('RS', 'Serbia', NULL, NULL, FALSE, 0),
  ('RU', 'Russia', NULL, NULL, FALSE, 0),
  ('RW', 'Rwanda', NULL, NULL, FALSE, 0),
  ('SA', 'Saudi Arabia', 'المملكة العربية السعودية', 'B', FALSE, 2),
  ('SB', 'Solomon Islands', NULL, NULL, FALSE, 0),
  ('SC', 'Seychelles', NULL, NULL, FALSE, 0),
  ('SD', 'Sudan', NULL, NULL, FALSE, 0),
  ('SE', 'Sweden', NULL, NULL, FALSE, 0),
  ('SG', 'Singapore', NULL, NULL, FALSE, 0),
  ('SH', 'St. Helena', NULL, NULL, FALSE, 0),
  ('SI', 'Slovenia', NULL, NULL, FALSE, 0),
  ('SJ', 'Svalbard & Jan Mayen', NULL, NULL, FALSE, 0),
  ('SK', 'Slovakia', NULL, NULL, FALSE, 0),
  ('SL', 'Sierra Leone', NULL, NULL, FALSE, 0),
  ('SM', 'San Marino', NULL, NULL, FALSE, 0),
  ('SN', 'Senegal', NULL, NULL, FALSE, 0),
  ('SO', 'Somalia', NULL, NULL, FALSE, 0),
  ('SR', 'Suriname', NULL, NULL, FALSE, 0),
  ('SS', 'South Sudan', NULL, NULL, FALSE, 0),
  ('ST', 'São Tomé & Príncipe', NULL, NULL, FALSE, 0),
  ('SV', 'El Salvador', NULL, NULL, FALSE, 0),
  ('SX', 'Sint Maarten', NULL, NULL, FALSE, 0),
  ('SY', 'Syria', 'سوريا', 'E:1', TRUE, 5),
  ('SZ', 'Eswatini', NULL, NULL, FALSE, 0),
  ('TC', 'Turks & Caicos Islands', NULL, NULL, FALSE, 0),
  ('TD', 'Chad', NULL, NULL, FALSE, 0),
  ('TF', 'French Southern Territories', NULL, NULL, FALSE, 0),
  ('TG', 'Togo', NULL, NULL, FALSE, 0),
  ('TH', 'Thailand', NULL, NULL, FALSE, 0),
  ('TJ', 'Tajikistan', NULL, NULL, FALSE, 0),
  ('TK', 'Tokelau', NULL, NULL, FALSE, 0),
  ('TL', 'Timor-Leste', NULL, NULL, FALSE, 0),
  ('TM', 'Turkmenistan', NULL, NULL, FALSE, 0),
  ('TN', 'Tunisia', NULL, NULL, FALSE, 0),
  ('TO', 'Tonga', NULL, NULL, FALSE, 0),
  ('TR', 'Turkey', NULL, NULL, FALSE, 0),
  ('TT', 'Trinidad & Tobago', NULL, NULL, FALSE, 0),
  ('TV', 'Tuvalu', NULL, NULL, FALSE, 0),
  ('TW', 'Taiwan', NULL, NULL, FALSE, 0),
  ('TZ', 'Tanzania', NULL, NULL, FALSE, 0),
  ('UA', 'Ukraine', NULL, NULL, FALSE, 0),
  ('UG', 'Uganda', NULL, NULL, FALSE, 0),
  ('UM', 'U.S. Outlying Islands', NULL, NULL, FALSE, 0),
  ('US', 'United States', 'الولايات المتحدة', 'A:1', FALSE, 0),
  ('UY', 'Uruguay', NULL, NULL, FALSE, 0),
  ('UZ', 'Uzbekistan', NULL, NULL, FALSE, 0),
  ('VA', 'Vatican City', NULL, NULL, FALSE, 0),
  ('VC', 'St. Vincent & Grenadines', NULL, NULL, FALSE, 0),
  ('VE', 'Venezuela', NULL, NULL, FALSE, 0),
  ('VG', 'British Virgin Islands', NULL, NULL, FALSE, 0),
  ('VI', 'U.S. Virgin Islands', NULL, NULL, FALSE, 0),
  ('VN', 'Vietnam', NULL, NULL, FALSE, 0),
  ('VU', 'Vanuatu', NULL, NULL, FALSE, 0),
  ('WF', 'Wallis & Futuna', NULL, NULL, FALSE, 0),
  ('WS', 'Samoa', NULL, NULL, FALSE, 0),
  ('YE', 'Yemen', NULL, NULL, FALSE, 0),
  ('YT', 'Mayotte', NULL, NULL, FALSE, 0),
  ('ZA', 'South Africa', NULL, NULL, FALSE, 0),
  ('ZM', 'Zambia', NULL, NULL, FALSE, 0),
  ('ZW', 'Zimbabwe', NULL, NULL, FALSE, 0)
ON CONFLICT (code) DO NOTHING;
